### ISSUE TITLE
トップ画面に存在する『やさしい　にほんご』へ遷移しない現象について

### ISSUE THREAD

**Issue by kkron4221** [mizphses/yosin-generator#11]
私の環境の問題かもしれませんが、トップページの予約ジェネレータの『やさしい　にほんご』選択時のみ『500 Internal Server Error』を引き起こします。
ソースコードを拝見させていただいた所、templatesでは"easy_ja.html"ですが、app.pyでは"easyja.html"に遷移となっているために引き起っている問題なのかと考えております。
そのため、どちらかに統一すれば解消されるのではないでしょうか？
ただリンクから直接easyjaを選択した場合404エラーを吐くのでもっと別の要因も考えられますが・・・
場合によっては機能自体を削除されるのも手なのではと思います。

**Comment by mizphses** [comment]
ご連絡ありがとうございます。
ただいま修正いたしました。

**Comment by mizphses** [comment]
なお、404を吐くのは予期されている仕様となっております。
（ルーティング上にeasyjaが定義されていないので、存在しないものを参照していると処理されるようです）

**Comment by kkron4221** [comment]
素早い対応ありがとうございます！
ルーティングの処理については確認しそびれていました。
大変失礼いたしました。
