### ISSUE TITLE
追加接種向け予診票への対応

### ISSUE THREAD

**Issue by Je3-6690** [mizphses/yosin-generator#12]
前回の接種では非常にお世話になりました。
医療従事者、高齢者向けの追加接種が始まるため、追加接種向けの予診票への対応をお願いしたいです。

**Comment by mizphses** [comment]
ご連絡ありがとうございます。
ただいま対応致しましたので，こちらのissueはクローズさせていただきます。

**Comment by Je3-6690** [comment]
ありがとうございます。
入居者分全員手書きの負担がなくなりました。
