### ISSUE TITLE
「やさしいにほんご」バージョンの編集

### ISSUE THREAD

**Issue by Lunefh** [mizphses/yosin-generator#4]
私はPython使えないのですが、
今ある英語版のhtmlファイルの、テキスト部分を置き換えれば作れる気がします。
あわせて英語版のスペルチェック等々もお手伝いできればと思うのですが、如何でしょうか？
（GitHub、Watchにしか使ったことがない初心者なので、検索しながらになりますがそれでもよければ…）

**Comment by mizphses** [comment]
お願いします！
なお，Q2~Q13の質問文につきましては厚労省の提供する文章をそのままコピペしてますので，そこは改変しないようお願いいたします．
（選択肢等は改変していただいてOKです）

やさしい日本語用のファイルも用意しておきますので（easy_ja.html），HTMLファイルの方の編集をお願いします．
このレポジトリをFolkしていただき，Pull Requestを送信してください．その際にサーバー側の統合処理も行います．

**Comment by Lunefh** [comment]
すみません！
ファイルは出来たのですが、どうやってこちらに送信したらいいのかがわかりません😢
GitHubDesktopというのを使っているのですが、
どうすればいいでしょう…
ちなみに自分のレポジトリではこちらに表示されているようです↓
https://github.com/Lunefh/yosin-generator/commit/2e5e0f050232798c726bde8a32fafa9c9f07df8d

**Comment by mizphses** [comment]
ありがとうございます。
以降こちらで処理させていただきます。制作ありがとうございました！

**Comment by Lunefh** [comment]
ありがとうございます
お手数おかけしますm(_ _)m
