### ISSUE TITLE
電話番号入力でiOSではハイフンが入力できない

### ISSUE THREAD

**Issue by TakumaNakagame** [mizphses/yosin-generator#6]
## 概要
iOSでフォームを利用した際、電話番号の入力画面にてハイフンが入力できません。
該当のフォームをフォーカスした際、キーボードが指定されるようですが、次の図のようにハイフンキーがないため、入力できません。

![image](https://user-images.githubusercontent.com/5129906/132134289-ec7ac8e0-be10-4170-8ed7-7ecb30b9c0f0.png)

## 求める結果
以下のいずれか
- ハイフンを利用しない
- ハイフンを打てるようにキーボードの変更を許可する

## その他情報
- iPhone 11
- iOS `14.7.1`

**Comment by mizphses** [comment]
キーボードの変更の許可が多分一番早いですね．
起床次第バリデーションで対応します．

iPhone実機持ってないのでご報告ありがとうございます．
